eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
turbine:
  app-config-list: yang-cloud-oauth2-server, yang-cloud-service-cms # 指定需要收集监控信息的服务名
  cluster-name-expression: "default" # 指定集群名称为default
  combine-host-port: true