eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
debug: true
spring:
  thymeleaf:
    encoding: utf-8
    cache: false
    mode: HTML5
  devtools:
    livereload:
      port: 35722
logging:
  level:
    org.springframework.security: debug