eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
debug: true
spring:
  thymeleaf:
    encoding: utf-8
    cache: false
    mode: HTML5
  devtools:
    livereload:
      port: 35722
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yang_cloud_2
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
logging:
  level:
    org.springframework.security: debug
    org.mybatis: debug
mybatis:
  type-aliases-package: cn.codeyang.pojo
  mapper-locations: classpath*:cn/codeyang/mapper/*.xml
  config-location: classpath:mybatis-config.xml
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql