eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
logging:
  level:
    root: debug
    org.springframework.security: debug
    org.springframework.cloud: debug
debug: false
security:
  oauth2:
    resource:
      token-info-uri: http://localhost:8762/oauth2/oauth/check_token
      prefer-token-info: true
    client:
      client-id: cms-web
      client-secret: secret
      access-token-uri: http://localhost:8762/oauth2/oauth/token
      user-authorization-uri: http://localhost:8762/oauth2/oauth/authorize
      scope: cms-web
management:
  security:
    enabled: false
  context-path: /cms
  port: 9003
hystrix.
