eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
spring:
  devtools:
    livereload:
      port: 35723
  datasource:
    url: jdbc:mysql://localhost:3306/yang_cloud_2
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password:
logging:
  level:
    root: info
    org.springframework.orm: debug
    org.springframework.security: debug
debug: false
security:
  oauth2:
    resource:
      token-info-uri: http://localhost:8762/oauth2/oauth/check_token
      prefer-token-info: true  #是否使用token-info  当使用user-info时设置为false即可
    sso:
      login-path: /login
    client:
      client-id: client
      client-secret: secret
      access-token-uri: http://localhost:8762/oauth2/oauth/token
      user-authorization-uri: http://localhost:8762/oauth2/oauth/authorize
management:
  security:
    enabled: false
mybatis:
  type-aliases-package: cn.codeyang.pojo
  mapper-locations: classpath*:cn/codeyang/mapper/*.xml
  config-location: classpath:mybatis-config.xml