eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/yang_cloud_2
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
  devtools:
    livereload:
      port: 35723
logging:
  level:
    root: info
    org.springframework.orm: debug
    org.springframework.security: debug
debug: true
security:
  oauth2:
    resource:
      token-info-uri: http://localhost:8762/oauth/check_token
      prefer-token-info: true  #是否使用token-info  当使用user-info时设置为false即可
    sso:
      login-path: /login
    client:
      client-id: client
      client-secret: secret
      access-token-uri: http://localhost:8762/oauth/token
      user-authorization-uri: http://localhost:8762/oauth/authorize
management:
  security:
    enabled: false